config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  get '/home' => 'home#index', as: "home"

  # Home Route
  get "/home/load" => "home#load_content", as: "load_content"

  # Dome Route
  resources :dome, controller: "dome", only: [:index]
  get "/dome/:place_type" => 'dome#show_place_type', as: "show_place_type"
  get "/dome/show/all" => 'dome#show_all', as: "show_all"
  get "/dome/guests/:no1-:no2" => 'dome#show_by_guests', as: "show_by_guests"
  get "/dome/price/:no1-:no2" => 'dome#show_by_price', as: "show_by_price"


  # Listings Routes
  resources :listings, controller: "listings", only: [:show] do
    # Review Route
    resources :reviews, controller: "review", only: [:new, :create]
    get 'booked_dates' => 'reservations#booked_dates'
    # Reservations Route
    post 'reservations/review_booking', as: 'review_booking'
    resources :reservations do
      # Payment
      get 'payment/new'
      post 'payment/checkout'
    end
  end


  get '/my-listings' => 'listings#my_index', as: "my_listings"
  get '/my-listings/new' => 'listings#new', as: "new_listing"
  post '/my-listings/new' => 'listings#create'
  get '/my-listings/:id/edit' => 'listings#edit', as: "edit_listing"
  get '/get_property_from_place_type' => 'listings#property_from_place_type'
  delete '/my-listings/:id' => "listings#destroy", as: "delete_listing"
  get "/listing/:id/upload-photos" => 'listings#show_upload', as: "show_upload"
  post '/listings/:id/upload-photos' => "listings#upload_photos", as: "listing_upload_photos"
  delete '/listings/:id/remove-photo/:index' => "listings#remove_photo", as: "listing_remove_photo"
  get '/listings/:id/view-photos' => "listings#view_photos", as: "view_photos"

  get '/forgot-password' => 'passwords#new', as: 'forgot_password'
  resources :password, controller: "passwords", only: [:create]

  # Users Routes
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "passwords",
      only: [:edit, :update]

    get 'account' => 'account#index', as: 'account_settings'
    get 'account/security' => 'account#security', as: 'account_settings_security'
    patch 'account/security/password-update' => 'account#update_password', as: 'account_settings_password_update'
  end
  get "/sign_up" => "users#new", as: "sign_up"
  get "/profile/:id" => "users#show", as: "profile"
  get "/profile/:id/edit" => "users#edit", as: "user_edit"
  patch "/profile/:id/edit" => "users#update", as: "user"
  get "/:id/upload-photo" => "users#upload_photo", as: "user_upload_photo"
  get "/:id/remove-photo" => "users#remove_photo", as: "user_remove_photo"

  # Superadmin
  constraints Clearance::Constraints::SignedIn.new { |user| user.superadmin? } do
  get "/admin-panel" => "superadmin#index", as: "admin_panel"
  get "/all-users" => "superadmin#all_users", as: "view_users"
  get "/update-users" => "superadmin#update_users", as: "update_users"
  delete "/delete/:id" => "superadmin#destroy_user", as: "destroy_user"
  get "/update/:id" => "superadmin#edit_user", as: "edit_user"
  patch "/update/:id" => "superadmin#confirm_edit", as: "superadmin_edit_user"
  get "/admin/search" => "superadmin#search", as: "search_user"
  end
  # Moderator
  constraints Clearance::Constraints::SignedIn.new { |user| user.moderator? || user.superadmin? } do
  get "/moderator-panel" => "moderator#index", as: "moderator_panel"
  get "/unverified_listings" => "moderator#unverified_listings", as: "unverified_listings"
  post "/unverified_listings/:id/verify/:verified" => "moderator#verify"
  get "/verified-listings" => "moderator#verified_listings", as: "verified_listings"
  get "/all-listings" => "moderator#all_listings", as: "all_listings"
  get "/view-listing/:id" => "moderator#view_listing", as: "view_listing"
  get "/moderator-edit-listing/:id" => "moderator#edit_listing", as: "moderator_edit_listing"
  get "/moderator-delete-listing/:id" => "moderator#delete_listing", as: "moderator_delete_listing"
  delete "/moderator-delete-listing/:id" => "moderator#destroy_listing", as: "moderator_destroy_listing"
  get "/moderator/search" => 'moderator#search', as: 'search_listing'
  end
  # Sessions Routes
  resource :session, controller: "sessions", only: [:create]
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  # Google OAuth Route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/models/listing.rb
class Listing < ApplicationRecord
  include PgSearch
  belongs_to :user
  delegate :id, :avatar, :first_name, :last_name, :birthday, :email, :phone, :country, :gender, :about_me, to: :user, prefix: true
  has_many :reviews
  has_many :reservations

  mount_uploaders :photos, PhotoUploader
  acts_as_taggable

  validates :name, presence: true
  validates :country, presence: true
  validates :state, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :place_type, presence: true
  validates :property_type, presence: true

  multisearchable :against => [:name, :country, :state, :address, :city, :place_type, :property_type, :price, :tag_list], using: [:tsearch, :trigram, :dmetaphone]

  pg_search_scope :search_by_name, :against => :name,
    using: [:tsearch]

  def self.search(search)
    if search
      name = Listing.where(name: search.titleize)
      country = Listing.where(country: search.upcase)
      state = Listing.where(state: search.titleize)
      city = Listing.where(city: search.titleize)
      address = Listing.where(address: search.titleize)
      property_type = Listing.where(property_type: search.titleize)
      place_type = Listing.where(place_type: Listing.string_to_place_type(search.titleize))
      {
        Names: name,
        Home: property_type,
        Place: place_type,
        Countries: country,
        States: state,
        Cities: city,
        Addresses: address
      }

    else
      Listing.all
    end
  end

  def self.place_type_string(data)
    if  data == 1
      "Apartment"
    elsif  data == 2
      "House"
    elsif  data == 3
      "Secondary Unit"
    elsif  data == 4
      "Unique Space"
    elsif data == 5
      "Boutique Hotel"
    else
      "Select One"
    end
  end

  def self.string_to_place_type(data)
    if  data == "Apartment"
      return 1
    elsif  data == "House"
      return 2
    elsif  data == "Secondary Unit"
      return 3
    elsif  data == "Unique Space"
      return 4
    elsif data == "Boutique Hotel"
      return 5
    end
  end

  def self.all_place_type
    all_place_type = ["Apartment", "House", "Secondary Unit", "Unique Space", "Boutique Hotel"]
  end

  def self.all_title
    all_title = ["Look for more Homes","One does not stay for one night!","Who needs a house, when you selldome live in one!","Browse for More!"]
  end

  def self.verified?(data)
    if data == true
      "Yes"
    elsif data == false
      "No"
    end
  end

  def country_name
     full_country = ISO3166::Country[country]
     full_country.translations[I18n.locale.to_s] || full_country.name
  end

  def property_from_place_type
    place = params[:place_type]
    if place == '1'
      @property_type = ["Apartment", "Condominium", "Casa particular (Cuba)", "Loft", "Serviced Apartment"]
    elsif place == '2'
      @property_type = ["House", "Bungalow", "Cabin", "Casa particular (Cuba)", "Chalet", "Cottage", "Cycladic House", "Dammuso (Italy)", "Dome House", "Earth House", "Farmstay", "Houseboat", "Hut", "Lighthouse", "Pension (South Korea)", "Shepherd's Hut (UK, France)", "Tiny House", "Townhouse", "Trullo (Italy)", "Villa"]
    elsif place == '3'
      @property_type = ["Guesthouse","Guest Suite","Farmstay"]
    elsif place == '4'
      @property_type = ["Barn", "Boat", "Bus", "Camper/RV", "Campsite", "Castle", "Cave", "Dome House", "Earth House", "Farmstay", "Hut", "Igloo, Island", "Lighthouse", "Pension (South Korea)", "Plane", "Shepherd's Hut (UK, France)", "Tent", "Tinyhouse", "Tipi", "Train", "Treehouse", "Windmill", "Yurt"]
    elsif place == '5'
      @property_type = ["Boutique Hotel", "Aparthotel", "Heritage Hotel (India)", "Hostel", "Hotel", "Natural Lodge", "Resort", "Serviced Apartment"]
    end
    render json: {property_type: @property_type}
  end
private
  def remove_image_at_index(index)
  remain_photos = self.photos
      if index == 0 && self.photos.size == 1
          self.remove_photos!
      else
          deleted_photo = remain_photos.delete_at(index)
          deleted_photo.try(:remove!)
          self.photos = remain_photos
      end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :require_login
  def my_index
    @user = current_user
    render 'listings/index'
  end

  def new
    @listing = Listing.new
  end

  def show
    @listing = Listing.includes(:reviews, :reservations).find(params[:id])
    @review = @listing.reviews.build
    @reservations = Reservation.where(listing_id: params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @listing = current_user.listings.build(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to my_listings_path
    else
      flash[:danger] = @listing.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update_attributes(listing_params)
      flash[:success] = "Listing successfully updated!"
      redirect_to listing_path(@listing.id)
    else
      flash[:danger] = "Update Failed!"
      redirect_back(fallback_location: root_path)
    end
  end

  def upload_photos
    new_photos = listing_params[:photos]
    @listing = Listing.find(params[:id])
    photos = @listing.photos
    photos += new_photos
    @listing.photos = photos
    if @listing.save
      flash[:success] = "Photo(s) uploaded!"
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "Error Occured"
      redirect_back(fallback_location: root_path)
    end
  end

  def show_upload
    @listing = Listing.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def remove_photo
    @listing = Listing.find(params[:id])
    @listing.remove_image_at_index(params[:index].to_i)
    if @listing.save
      flash[:success] = "Photo removed"
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "Error Occured"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to my_listings_path
  end

  def view_photos
    @listing = Listing.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def property_from_place_type
    place = params[:place_type]
    if place == '1'
      @property_type = ["Apartment", "Condominium", "Casa particular (Cuba)", "Loft", "Serviced Apartment"]
    elsif place == '2'
      @property_type = ["House", "Bungalow", "Cabin", "Casa particular (Cuba)", "Chalet", "Cottage", "Cycladic House", "Dammuso (Italy)", "Dome House", "Earth House", "Farmstay", "Houseboat", "Hut", "Lighthouse", "Pension (South Korea)", "Shepherd's Hut (UK, France)", "Tiny House", "Townhouse", "Trullo (Italy)", "Villa"]
    elsif place == '3'
      @property_type = ["Guesthouse","Guest Suite","Farmstay"]
    elsif place == '4'
      @property_type = ["Barn", "Boat", "Bus", "Camper/RV", "Campsite", "Castle", "Cave", "Dome House", "Earth House", "Farmstay", "Hut", "Igloo, Island", "Lighthouse", "Pension (South Korea)", "Plane", "Shepherd's Hut (UK, France)", "Tent", "Tinyhouse", "Tipi", "Train", "Treehouse", "Windmill", "Yurt"]
    elsif place == '5'
      @property_type = ["Boutique Hotel", "Aparthotel", "Heritage Hotel (India)", "Hostel", "Hotel", "Natural Lodge", "Resort", "Serviced Apartment"]
    end
    render json: {property_type: @property_type}
  end

  private

  def listing_params
    params.require(:listing).permit(
      :name,
      :place_type,
      :property_type,
      :room_number,
      :bathroom_number,
      :guest_number,
      :country,
      :state,
      :city,
      :zipcode,
      :address,
      :price,
      :description,
      :user_id,
      :tag_list,
      :verified,
      {photos: []},
      :instant_booking,
      review_attributes: [:id, :rating, :comment, :user_id]
    )
  end
end

app/views/listings/_view_photos.html.erb
<div id="carousel-modal" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% @listing.photos.each_with_index do |photo, index| %>
        <% if index == 0 %>
            <div class="carousel-item active">
              <%=image_tag(photo.url, class: 'd-block w-100')%>
            </div>
        <% else %>
            <div class="carousel-item">
              <%=image_tag(photo.url, class: 'd-block w-100')%>
            </div>
        <% end %>
    <%end%>
  </div>
  <a class="carousel-control-prev" href="#carousel-modal" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-modal" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/listings/edit.html.erb
<div class="background-keep">
  <div class="mt-5 container-fluid p-0">
        <h5 class="font-weight-bold">Edit Listing: <%= @listing.name %></h5>
  </div>

  <div class="container-fluid p-0">
    <%= render partial: 'listings/form-edit'%>
  </div>
</div>

<div id="modal-upload-photo-listing" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<% content_for :navbar do %>
  <% if signed_in? %>
    <%= render partial: "shared/navbar" %>
  <% else %>
    <%= render partial: "shared/navbar-index" %>
  <% end %>
<% end %>
<%=form_tag(dome_index_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search], class: "searchbox-sm shadow-sm form-control mb-4", placeholder: "Search anything...") %>
<% end %>
<div class="background-keep">
  <div class="mt-5 container-fluid p-0">
    <ul class="list-inline">
      <li class="list-inline-item">
        <h5 class="font-weight-bold">My Listings</h5>
      </li>

      <li class="list-inline-item float-right">
        <a href="my-listings/new"class="btn btn-outline-dark">Create a listing</a>
      </li>
    </ul>
  </div>

  <div class="container-fluid p-0">
      <%= render partial: 'listings/my-listing.html.erb'%>
  </div>
</div>

app/views/listings/new.html.erb
<div class="background-keep">
  <div class="container-fluid my-5 p-0">
    <h5 class="">Create a List</h5>

    <%= render partial: 'listings/form'%>

  </div>
</div>

app/views/listings/profile.html.erb
<% content_for :navbar do %>
  <% if signed_in? %>
    <%= render partial: "shared/navbar" %>
  <% else %>
    <%= render partial: "shared/navbar-index" %>
  <% end %>
<% end %>

<% if @listing.photos? == true %>
<div class="cover-photo" style="background-image: url('<%=@listing.photos[0].url%>');">
<%=link_to "View Photos", view_photos_path(@listing.id), remote:true, class:'view-photos btn btn-outline-light'%>
<% else %>
<div class="cover-photo bg-dark" style="background-image: url('assets/default-no-photos.jpg');">
<% end %>
</div>

<!-- View Photos Modal -->
<div class="modal fade" id="view-photos-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>



<% if current_user.moderator? || current_user.superadmin? %>
<div class="d-flex justify-content-center p-3 bg-success">
  <%=link_to "Edit", moderator_edit_listing_path, remote:true, class: 'btn btn-warning p-2 px-5 m-2'%>
  <%= button_to 'Delete', moderator_destroy_listing_path(@listing.id),  method: "delete", remote: true , data: {confirm: "Are you sure you want to delete this?"}, class: 'btn btn-danger p-2 px-5 m-2' %>
</div>
<div class="modal fade" id="mod-edit-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Listing ID <%=@listing.id%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>
<% end %>
<div class="container mx-auto d-block">
  <div class="container-fluid p-0 mt-5">
    <div class="row">
      <div class="col-8">
        <div class="row">
          <div class="col">
            <div class="d-flex">
              <h1 class="font-weight-bold mb-0 mr-1"><%=@listing.name%></h1>
              <% if @listing.verified %>
                <p id="verified-text" class=""><i id="verified-badge" class="fas fa-check-circle text-success"></i> Verified Listing</p>
              <% end %>
            </div>
            <p class="text-muted p-0"><%=@listing.property_type%></p>
            <p class="text-muted"><%=@listing.state%></p>
            <ul class="inline-item p-0">
              <li class="list-inline-item"><i class="fas fa-user"></i> <%=@listing.guest_number%> guests</li>
              <li class="list-inline-item mx-3"><i class="fas fa-bed"></i> <%=@listing.room_number%> Bedrooms</li>
              <li class="list-inline-item"><i class="fas fa-bath"></i> <%=@listing.bathroom_number%> Bathrooms</li>
            </ul>
          </div>
          <div class="col">
            <a href="/profile/<%=@listing.user_id%>"><div class="profile-photo mx-auto" style= "background-image: url('<%=@listing.user.avatar.url%>');"></div></a>
            <p class="text-muted text-center mt-1"><%=@listing.user.name%></p>
          </div>
        </div>

        <div class="card my-5">
          <div class="card-body">
            <p class="card-title text-muted">Home Hightlights</p>
            <ul class="list-inline m-0">
            <%@listing.tag_list.each do |tag|%>
              <li class="list-inline-item"><p class="card-text btn btn-outline-secondary"><%=tag%></p></li>
            <% end %>
            </ul>
          </div>
        </div>

        <div id="description" class="collapse" aria-labelledby="description" data-parent="#description">
            <p><%=@listing.description%></p><a role="button" class="collapsed" data-toggle="collapse" href="#collapseExample"
         aria-expanded="false" aria-controls="collapseExample"></a>
        </div>
        <button id="view-more" class="btn btn-link p-0 my-2 font-weight-bold" data-toggle='collapse' data-target='#description' aria-expanded='true' aria-controls= 'description'>
          Read more about this space.
        </button></br>
        <a href="" class="btn btn-link p-0 font-weight-bold text-dark my-4">Contact Host</a>
        <hr/>
        <p class="font-weight-bold mt-5">Availability</p>
        <p>RESERVED: CALENDAR FOR RESERVATION</p>
        <hr/>
        <div id="review-box">
          <% if @listing.reviews.any? %>
          <h3 class="font-weight-bold"><%=@listing.reviews.count%> Reviews</h3>
          <% else %>
          <h3 class="font-weight-bold">No Reviews yet.</h3>
          <% end %>
          <div class="rating-box my-4">
            <ul id="star-rating" class="list-inline">
              <li class="list-inline-item star"><i data-value='1' id="star-<%=@listing.id%>" class="rate-star far fa-star"></i></li>
              <li class="list-inline-item star"><i data-value='2' id="star-<%=@listing.id%>" class="rate-star far fa-star"></i></li>
              <li class="list-inline-item star"><i data-value='3' id="star-<%=@listing.id%>" class="rate-star far fa-star"></i></li>
              <li class="list-inline-item star"><i data-value='4' id="star-<%=@listing.id%>" class="rate-star far fa-star"></i></li>
              <li class="list-inline-item star"><i data-value='5' id="star-<%=@listing.id%>" class="rate-star far fa-star"></i></li>
              <li class="list-inline-item">
                <p id="rate-text" class="text-muted m-0"><%=@listing.reviews.count%> people has left a review.</p>
              </li>
            </ul>
          </div>
          <%= form_for [@listing, Review.new] do |f|%>
            <%= f.hidden_field :rating%>
            <div class="form-group">
              <%= f.label "Comment", class: 'text-weight-bold'%>
              <%= f.text_area :comment, class: 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.submit "Leave A Review", class: 'btn btn-secondary'%>
            </div>
          <% end %>
        </div>




        <hr/>

        <% @listing.reviews.all.limit(10).each do |comment| %>
        <div class="card border-0">
          <ul class="list-inline">
            <li class="list-inline-item float-left">
              <a href="/profile/<%=comment.user_id%>"><div class="profile-thumbnail m-0 p-0 " style='background-image: url("<%=comment.user.avatar.url%>")'></div></a>
            </li>
            <li class="list-inline-item float-left">
              <p class="font-weight-bold m-0 align-top"><%=comment.user.name%></p>
              <p class="text-muted m-0 align-top"><%=Time.now.strftime("%B %Y")%></p>
              <% if comment.rating == 0 %>
              <div class="rating-box">
                <ul id="star-rating" class="list-inline">
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                </ul>
              </div>

              <% elsif comment.rating == 1 %>
              <div class="rating-box">
                <ul id="star-rating" class="list-inline">
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                </ul>
              </div>

              <% elsif comment.rating == 2 %>
              <div class="rating-box">
                <ul id="star-rating" class="list-inline">
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                </ul>
              </div>

              <% elsif comment.rating == 3 %>
              <div class="rating-box">
                <ul id="star-rating" class="list-inline">
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                </ul>
              </div>

              <% elsif comment.rating == 4 %>
              <div class="rating-box">
                <ul id="star-rating" class="list-inline">
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font far fa-star"></i></li>
                </ul>
              </div>

              <% elsif comment.rating == 5 %>
              <div class="rating-box">
                <ul id="star-rating" class="list-inline">
                  <li class="list-inline-item"><i class="text-muted tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item"><i class="text-muted tiny-font rate-star fas fa-star"></i></li>
                </ul>
              </div>
              <% end %>
            </li>
          </ul>
          <p class=""><%=comment.comment%></p>
        </div>
        <hr/>
      <% end %>
      </div>

      <div class="col-4">
        <div class="card sticky-top sticky-offset">
          <div class="card-body ">
            <h4 class="card-title font-weight-bold">$<%=@listing.price.to_i%> <span class="tiny-font">per night</span></h4>
            <hr/>
            <button class="btn btn-danger px-5 mx-auto d-block">Book</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('#star-rating li').on('mouseover',function(){
    let onStar = parseInt($(this).children('i.rate-star').data('value'),10);

    $(this).parent().children('li.star').each(function(s){
      if (s < onStar) {
        $(this).children('i.rate-star').removeClass('far').addClass('fas');
      }
      else {
        $(this).children('i.rate-star').removeClass('fas').addClass('far');
      }
    })

  })


  $('.rate-star').on('click', function(){
    let onStar = $(this).data('value');
    let stars = $(this).parent().children('li.star');

    for (i=0; i < onStar.length; i++) {
      $(stars[i]).children('i.rate-star').removeClass('far').addClass('fas');
    }

    $('#rate-text').html('You rated ' + onStar + ' stars');

    $('input[name="review[rating]"]').val(onStar)
  });
</script>

app/views/listings/show.js.erb
$("#events_calendar").html("<%= escape_javascript render(partial: 'reservations/calendar', locals: {events: @reservations}) %>");

app/views/listings/show_upload.js.erb
$('#modal-upload-photo-listing').find('.modal-content').html('<%= j render "shared/modal-upload-photos-listing"%>');
$('#modal-upload-photo-listing').modal('show');

app/views/listings/upload_photos.js.erb
$("#listing-upload-box").find(".modal-content").html("<%= j render 'shared/modal-upload-photos-listing' %>");
$("#listing-upload-box").modal('show');

app/views/listings/view_photos.js.erb
$('#view-photos-modal').find('.modal-content').html('<%= j render "listings/view_photos"%>');
$('#view-photos-modal').modal('show');