config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  get '/home' => 'home#index', as: "home"

  # Home Route
  get "/home/load" => "home#load_content", as: "load_content"

  # Dome Route
  resources :dome, controller: "dome", only: [:index]
  get "/dome/:place_type" => 'dome#show_place_type', as: "show_place_type"
  get "/dome/show/all" => 'dome#show_all', as: "show_all"
  get "/dome/guests/:no1-:no2" => 'dome#show_by_guests', as: "show_by_guests"
  get "/dome/price/:no1-:no2" => 'dome#show_by_price', as: "show_by_price"


  # Listings Routes
  resources :listings, controller: "listings", only: [:show] do
    # Review Route
    resources :reviews, controller: "review", only: [:new, :create]
    get 'booked_dates' => 'reservations#booked_dates'
    # Reservations Route
    post 'reservations/review_booking', as: 'review_booking'
    resources :reservations do
      # Payment
      get 'payment/new'
      post 'payment/checkout'
    end
  end


  get '/my-listings' => 'listings#my_index', as: "my_listings"
  get '/my-listings/new' => 'listings#new', as: "new_listing"
  post '/my-listings/new' => 'listings#create'
  get '/my-listings/:id/edit' => 'listings#edit', as: "edit_listing"
  get '/get_property_from_place_type' => 'listings#property_from_place_type'
  delete '/my-listings/:id' => "listings#destroy", as: "delete_listing"
  get "/listing/:id/upload-photos" => 'listings#show_upload', as: "show_upload"
  post '/listings/:id/upload-photos' => "listings#upload_photos", as: "listing_upload_photos"
  delete '/listings/:id/remove-photo/:index' => "listings#remove_photo", as: "listing_remove_photo"
  get '/listings/:id/view-photos' => "listings#view_photos", as: "view_photos"

  get '/forgot-password' => 'passwords#new', as: 'forgot_password'
  resources :password, controller: "passwords", only: [:create]

  # Users Routes
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "passwords",
      only: [:edit, :update]

    get 'account' => 'account#index', as: 'account_settings'
    get 'account/security' => 'account#security', as: 'account_settings_security'
    patch 'account/security/password-update' => 'account#update_password', as: 'account_settings_password_update'
  end
  get "/sign_up" => "users#new", as: "sign_up"
  get "/profile/:id" => "users#show", as: "profile"
  get "/profile/:id/edit" => "users#edit", as: "user_edit"
  patch "/profile/:id/edit" => "users#update", as: "user"
  get "/:id/upload-photo" => "users#upload_photo", as: "user_upload_photo"
  get "/:id/remove-photo" => "users#remove_photo", as: "user_remove_photo"

  # Superadmin
  constraints Clearance::Constraints::SignedIn.new { |user| user.superadmin? } do
  get "/admin-panel" => "superadmin#index", as: "admin_panel"
  get "/all-users" => "superadmin#all_users", as: "view_users"
  get "/update-users" => "superadmin#update_users", as: "update_users"
  delete "/delete/:id" => "superadmin#destroy_user", as: "destroy_user"
  get "/update/:id" => "superadmin#edit_user", as: "edit_user"
  patch "/update/:id" => "superadmin#confirm_edit", as: "superadmin_edit_user"
  get "/admin/search" => "superadmin#search", as: "search_user"
  end
  # Moderator
  constraints Clearance::Constraints::SignedIn.new { |user| user.moderator? || user.superadmin? } do
  get "/moderator-panel" => "moderator#index", as: "moderator_panel"
  get "/unverified_listings" => "moderator#unverified_listings", as: "unverified_listings"
  post "/unverified_listings/:id/verify/:verified" => "moderator#verify"
  get "/verified-listings" => "moderator#verified_listings", as: "verified_listings"
  get "/all-listings" => "moderator#all_listings", as: "all_listings"
  get "/view-listing/:id" => "moderator#view_listing", as: "view_listing"
  get "/moderator-edit-listing/:id" => "moderator#edit_listing", as: "moderator_edit_listing"
  get "/moderator-delete-listing/:id" => "moderator#delete_listing", as: "moderator_delete_listing"
  delete "/moderator-delete-listing/:id" => "moderator#destroy_listing", as: "moderator_destroy_listing"
  get "/moderator/search" => 'moderator#search', as: 'search_listing'
  end
  # Sessions Routes
  resource :session, controller: "sessions", only: [:create]
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  # Google OAuth Route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/controllers/superadmin_controller.rb
class SuperadminController < ApplicationController
  before_action :require_login

    def index
      if current_user.superadmin?
        render 'superadmin/index'
      else
        flash[:danger] = "You have no access!"
        redirect_to root_path
      end
    end

    def all_users
      if current_user.superadmin?
        respond_to do |format|
          format.js
        end
      else
        flash[:danger] = "You have no access!"
        redirect_to root_path
      end
    end

    def update_users
      if current_user.superadmin?
        respond_to do |format|
          format.js
        end
      else
        flash[:danger] = "You have no access!"
        redirect_to root_path
      end
    end

    def destroy_user
      if current_user.superadmin?
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_panel_path
      else
        flash[:danger] = "You have no access!"
        redirect_to admin_panel_path
      end
    end

    def edit_user
      if current_user.superadmin?
        @user = User.find(params[:id])
        respond_to do |format|
          format.js
        end
      else
        flash[:danger] = "You have no access!"
        redirect_to admin_panel_path
      end
    end

    def confirm_edit
      if current_user.superadmin?
        @user = User.find(params[:id])
        @user.update_attributes(user_params)
        if @user.save
          flash[:warning] = "User has been edited"
          redirect_to admin_panel_path
        end
      else
        flash[:danger] = "You have no access!"
        redirect_to admin_panel_path
      end
    end

    def search
      if current_user.superadmin?
        respond_to do |format|
          format.js
        end
      else
        flash[:danger] = "You have no access!"
        redirect_to root_path
      end
    end

private

  def user_params
    params.require(:user)
        .permit(
          :first_name,
          :last_name,
          :country,
          :gender,
          :birthday,
          :email,
          :phone
        )
  end
end

app/views/superadmin/all_users.js.erb
$('#panel-box').html("<%= j render partial: 'shared/view-users' %>");

app/views/superadmin/edit-user.js.erb
$("#user-modal").find(".modal-content").html("<%= j render 'shared/modal-edit-user' %>");
$("#user-modal").modal('show');

app/views/superadmin/edit_user.js.erb
$("#user-modal").find(".modal-content").html("<%= j render 'shared/modal-edit-user' %>");
$("#user-modal").modal('show');

app/views/superadmin/index.html.erb
<% content_for :navbar_special do %>
  <%= render partial: "shared/navbar-panel" %>
<% end %>

<div class="container-fluid mt-5 p-0">
  <div class="d-flex flex-wrap flex-col">
    <div class="container-fluid">
      <div class="card ">
        <div class="card-body">
          <ul class="list-inline m-0">
            <li class="list-inline-item">
              <h3 class="m-0 font-weight-bold">Welcome <%=current_user.name%>!</h3>
            </li>
            <li class="list-inline-item">
              <h5 class="m-0 text-muted">Dashboard</h5>
            </li>
          </ul>
        </div>
      </div>
      <div class="navbar px-0 navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler m-2" type="button" data-toggle="collapse" data-target="#list-options" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-angle-down"></i>
        </button>

        <div class="collapse navbar-collapse" id="list-options">
          <ul class="list-inline m-0">
            <li class="list-inline-item">
              <%= link_to 'View Users', view_users_path, remote: true, data: { target: '#panel-box' }, class: 'text-light p-2' %>
            </li>
            <li class="list-inline-item">
              <%= link_to 'Update Users', update_users_path, remote: true, data: { target: '#panel-box' }, class: 'text-light p-2' %>
            </li>
            <!-- Listings -->
            <li class="list-inline-item">
              <%= link_to 'All Listings', all_listings_path, remote: true, data: { target: '#panel-box' }, class: 'text-light p-2' %>
            </li>
            <li class="list-inline-item">
              <%= link_to 'Unverified Listings', unverified_listings_path, remote: true, data: { target: '#panel-box' }, class: 'text-light p-2' %>
            </li>
            <li class="list-inline-item">
              <%= link_to 'Verified Listing', verified_listings_path, remote: true, data: { target: '#panel-box' }, class: 'text-light p-2' %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="card">
        <div id="panel-box" class="card-body">
          <p class="text-muted m-0">Choose a list.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="listing-modal" tabindex="-1" role="dialog" aria-labelledby="viewListing" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>

app/views/superadmin/search.js.erb
$('#panel-box').html("<%= j render partial: 'shared/search_users' %>");

app/views/superadmin/update-users.js.erb
$('#panel-box').html("<%= j render partial: 'shared/update-users' %>");

app/views/superadmin/update_users.js.erb
$('#panel-box').html("<%= j render partial: 'shared/update-users' %>");

app/views/superadmin/view-users.js.erb
$('#panel-box').html("<%= j render partial: 'shared/view-users' %>");