config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  get '/home' => 'home#index', as: "home"

  # Home Route
  get "/home/load" => "home#load_content", as: "load_content"

  # Dome Route
  resources :dome, controller: "dome", only: [:index]
  get "/dome/:place_type" => 'dome#show_place_type', as: "show_place_type"
  get "/dome/show/all" => 'dome#show_all', as: "show_all"
  get "/dome/guests/:no1-:no2" => 'dome#show_by_guests', as: "show_by_guests"
  get "/dome/price/:no1-:no2" => 'dome#show_by_price', as: "show_by_price"


  # Listings Routes
  resources :listings, controller: "listings", only: [:show] do
    # Review Route
    resources :reviews, controller: "review", only: [:new, :create]
    get 'booked_dates' => 'reservations#booked_dates'
    # Reservations Route
    post 'reservations/review_booking', as: 'review_booking'
    resources :reservations do
      # Payment
      get 'payment/new'
      post 'payment/checkout'
    end
  end


  get '/my-listings' => 'listings#my_index', as: "my_listings"
  get '/my-listings/new' => 'listings#new', as: "new_listing"
  post '/my-listings/new' => 'listings#create'
  get '/my-listings/:id/edit' => 'listings#edit', as: "edit_listing"
  get '/get_property_from_place_type' => 'listings#property_from_place_type'
  delete '/my-listings/:id' => "listings#destroy", as: "delete_listing"
  get "/listing/:id/upload-photos" => 'listings#show_upload', as: "show_upload"
  post '/listings/:id/upload-photos' => "listings#upload_photos", as: "listing_upload_photos"
  delete '/listings/:id/remove-photo/:index' => "listings#remove_photo", as: "listing_remove_photo"
  get '/listings/:id/view-photos' => "listings#view_photos", as: "view_photos"

  get '/forgot-password' => 'passwords#new', as: 'forgot_password'
  resources :password, controller: "passwords", only: [:create]

  # Users Routes
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "passwords",
      only: [:edit, :update]

    get 'account' => 'account#index', as: 'account_settings'
    get 'account/security' => 'account#security', as: 'account_settings_security'
    patch 'account/security/password-update' => 'account#update_password', as: 'account_settings_password_update'
  end
  get "/sign_up" => "users#new", as: "sign_up"
  get "/profile/:id" => "users#show", as: "profile"
  get "/profile/:id/edit" => "users#edit", as: "user_edit"
  patch "/profile/:id/edit" => "users#update", as: "user"
  get "/:id/upload-photo" => "users#upload_photo", as: "user_upload_photo"
  get "/:id/remove-photo" => "users#remove_photo", as: "user_remove_photo"

  # Superadmin
  constraints Clearance::Constraints::SignedIn.new { |user| user.superadmin? } do
  get "/admin-panel" => "superadmin#index", as: "admin_panel"
  get "/all-users" => "superadmin#all_users", as: "view_users"
  get "/update-users" => "superadmin#update_users", as: "update_users"
  delete "/delete/:id" => "superadmin#destroy_user", as: "destroy_user"
  get "/update/:id" => "superadmin#edit_user", as: "edit_user"
  patch "/update/:id" => "superadmin#confirm_edit", as: "superadmin_edit_user"
  get "/admin/search" => "superadmin#search", as: "search_user"
  end
  # Moderator
  constraints Clearance::Constraints::SignedIn.new { |user| user.moderator? || user.superadmin? } do
  get "/moderator-panel" => "moderator#index", as: "moderator_panel"
  get "/unverified_listings" => "moderator#unverified_listings", as: "unverified_listings"
  post "/unverified_listings/:id/verify/:verified" => "moderator#verify"
  get "/verified-listings" => "moderator#verified_listings", as: "verified_listings"
  get "/all-listings" => "moderator#all_listings", as: "all_listings"
  get "/view-listing/:id" => "moderator#view_listing", as: "view_listing"
  get "/moderator-edit-listing/:id" => "moderator#edit_listing", as: "moderator_edit_listing"
  get "/moderator-delete-listing/:id" => "moderator#delete_listing", as: "moderator_delete_listing"
  delete "/moderator-delete-listing/:id" => "moderator#destroy_listing", as: "moderator_destroy_listing"
  get "/moderator/search" => 'moderator#search', as: 'search_listing'
  end
  # Sessions Routes
  resource :session, controller: "sessions", only: [:create]
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  # Google OAuth Route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/views/shared/_all_listings.html.erb
<h5 class="font-weight-bold mb-4 text-center">All Listings</h5>
<%=form_tag(search_listing_path , method: :get, remote:true, class: "d-flex justify-content-center") do %>
<%= text_field_tag(:search, params[:search], class: "shadow-sm form-control m-3 mb-5  w-50", placeholder: "Search by Name") %>
<% end %>

<div class="d-flex flex-row">
  <div class="px-2  tiny-font flex-shrink-1 font-weight-bold">ID</div>
  <div class="px-2  tiny-font col-2 font-weight-bold">Name</div>
  <div class="px-2  tiny-font col-2 font-weight-bold">Property Type</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">Country</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">State</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">Price</div>
  <div class="px-2  tiny-font col-2 font-weight-bold">Host</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">Verified</div>
</div>
<hr/>
<% Listing.order(created_at: :asc).each do |listing|%>
  <%= link_to view_listing_path(listing.id), remote: true, data: { target: "#listing-modal", toggle: 'modal' } do %>
  <div class="d-flex flex-row">
    <div class="px-2  tiny-font flex-shrink-1 font-weight-bold"><%=listing.id%></div>
    <div class="px-2  tiny-font col-2"><%=listing.name%></div>
    <div class="px-2  tiny-font col-2"><%=listing.property_type%></div>
    <div class="px-2  tiny-font col-1"><%=listing.country%></div>
    <div class="px-2  tiny-font col-1"><%=listing.state%></div>
    <div class="px-2  tiny-font col-1"><%=number_to_currency(listing.price, unit: '$')%></div>
    <div class="px-2  tiny-font col-2"><%=listing.user.name%></div>
    <div class="px-2 tiny-font col-1">
      <% if listing.verified? %>
        <p class="font-weight-bold text-success">Verified</p>
      <% else %>
        <p class="font-weight-bold text-warning">Not Verified</p>
      <% end %>
    </div>
  </div>
  <% end %>
<hr/>
<% end %>

app/views/shared/_message_dropdown.html.erb
<p class="m-0 font-weight-bold">Messages</p>
<div class="dropdown-divider"></div>
<% current_user.listings.each do |listing|%>
  <% listing.reservations.order(created_at: :desc).each do |reservation| %>
    <a class="font-weight-bold" href="/profile/<%=reservation.user_id%>"><%=reservation.user_name%></a> booked <a class="font-weight-bold" href="/listings/<%=reservation.listing_id%>"><%=reservation.listing_name%></a> for <%=reservation.days%>!
    <p class="tiny-font text-muted"><%=reservation.created_at%></p>
    <% if reservation.paid? %>
    <p class="tiny-font text-muted">Paid </p>
    <% else %>
    <p class="tiny-font text-muted">Unpaid</p>
    <% end %>
    <div class="dropdown-divider"></div>
  <% end %>
<% end %>

<% current_user.reservations.order(created_at: :desc).each do |reservation|%>
  You have booked <a class="font-weight-bold" href="/listings/<%=reservation.listing_id%>"><%=reservation.listing_name%></a> for <%=reservation.days%>!
  <p class="m-0 tiny-font text-muted"><%=reservation.created_at%></p>
  <% if reservation.paid == true%>
  <p class="tiny-font text-muted">Paid </p>
  <% else %>
    <%=link_to listing_reservation_payment_new_path(reservation_id: reservation.id, listing_id: reservation.listing_id) do %>
    <p class="tiny-font text-muted">Unpaid</p>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_modal-sign-in.html.erb
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Sign In</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
   </div>
  <div class="modal-body">
      <div id="clearance" class="sign-in">

        <%= render partial: '/sessions/form' %>

      </div>
  </div>
  <div class="modal-footer">
</div>

app/views/shared/_modal-sign-up.html.erb
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Sign Up</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
   </div>
  <div class="modal-body">
      <div id="clearance" class="sign-up">

        <%= render partial: '/users/form' %>

      </div>
  </div>
  <div class="modal-footer justify-content-start">
    <div class="other-links">
      <%= link_to 'Sign In', sign_in_path , remote: true, data: { target: '#modal-signin', toggle: 'modal' }, class: 'btn btn-primary'%>
      <%= link_to "Sign in with Google", "/auth/google_oauth2", class: 'btn btn-danger list-inline-item' %>
    </div>
  </div>
</div>

app/views/shared/_modal-upload-photo-user.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Upload Profile Photo</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
  <span aria-hidden="true">&times;</span>
  </button>
  </div>
<div class="modal-body">
  <%= form_for :user , url: user_edit_path, method: 'PATCH' do |f|%>
  <div class="form-group">
    <%=f.label :avatar, "Upload via Computer:"%>
    <%=f.file_field :avatar, class: 'form-control-file'%>
  </div>
  <div class="form-group">
    <%=f.label "Upload via URL:"%>
    <%= f.text_field :remote_avatar_url , placeholder: "www.example.com/example.jpg",class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit "Upload Photo", class: 'btn' %>
  </div>
  <%end%>
</div>

app/views/shared/_modal-upload-photos-listing.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Upload Listing Photos</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
  <span aria-hidden="true">&times;</span>
  </button>
</div>
  <div class="modal-body">
    <%= form_for @listing, url: listing_upload_photos_path(@listing.id), method: 'post' do |form|%>
      <div  class="form-group">
      <%= form.label "Upload some photos of your home."%>
      <%= form.file_field :photos, multiple: true, class: 'form-control-file' %>
      </div>
      <div  class="form-group">
        <%= form.submit "Upload", class: 'btn btn-secondary'%>
      </div>
    <%end%>
  </div>

app/views/shared/_navbar-index.html.erb
<nav id="navBar-public" class="navbar navbar-expand-lg navbar-light bg-transparent fixed-top">
  <a class="navbar-brand font-weight-bold" href="/">Selldome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link font-weight-bold" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <% if signed_in? -%>
          <%= button_to(t(".sign_out"), sign_out_path, method: :delete, class: "btn p-0 bg-transparent font-weight-bold") %>
        <% else -%>
          <%= link_to 'Sign In', sign_in_path , remote: true, data: { target: '#modal-signin', toggle: 'modal' }, class: 'font-weight-bold nav-link'%>
        <% end -%>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_navbar-panel.html.erb
<nav id="navbar" class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- PROFILE BOX SM -->
  <div class="profile-box-sm">
    <a href="/profile/<%=current_user.id%>">
      <img class="rounded-circle" src="<%=current_user.avatar.url%>" style="width:35px;height:35px;">
    </a>
  </div>
  <% if current_user.superadmin?%>
  <a class="navbar-brand font-weight-bold" href="/">Selldome <span class="nav-text text-muted tiny-font">Admin</span></a>
  <% else %>
  <a class="navbar-brand font-weight-bold" href="/">Selldome <span class="nav-text text-muted tiny-font">Mod</span></a>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <!-- Messages -->
      <li class="nav-item">
        <a href="#" class="btn text-light">Messages</a>
      </li>
      <!-- Account Dropdown -->
      <li class="nav-item">
        <div class="dropdown mx-2">
          <a class="" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="rounded-circle" src="/assets/profile-photo.jpg" style="width:35px;height:35px;">
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/dome">Dome</a>
            <a class="dropdown-item" href="/home">Home</a>
            <div class="dropdown-divider"></div>
            <div id="header" class="btn dropdown-item">
              <% if signed_in? -%>
                <%= button_to(t(".sign_out"), sign_out_path, method: :delete, class: "btn p-0 bg-transparent") %>
              <% else -%>
                <%= link_to t(".sign_in"), sign_in_path, class: "btn p-0" %>
              <% end -%>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-white">
  <!-- PROFILE BOX SM -->
  <div class="profile-box-sm">
    <a href="/profile/<%=current_user.id%>">
      <img class="rounded-circle" src="<%=current_user.avatar.url%>" style="width:35px;height:35px;">
    </a>
  </div>

  <a class="navbar-brand font-weight-bold" href="/">Selldome</a>

  <%=form_tag(dome_index_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search], class: "searchbox shadow-sm form-control mr-sm-2", placeholder: "Search anything...") %>
  <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarDropdown" aria-controls="navbarDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



  <div class="collapse navbar-collapse" id="navbarDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <% if current_user.moderator?%>
        <%=link_to "Moderator Panel", moderator_panel_path, class: 'btn btn-outline-dark'%>
        <% elsif current_user.superadmin?%>
        <%=link_to "SuperAdmin Panel", admin_panel_path, class: 'btn btn-outline-dark'%>
        <% end %>
      </li>
      <!-- Saved -->
      <li class="nav-item">
        <a class="nav-link disabled">Saved</a>
      </li>
      <!-- My Listings -->
      <li class="nav-item">
        <a href="/my-listings" class="btn">My Listings</a>
      </li>
      <!-- Messages -->
      <li class="nav-item">
        <div class="dropdown">
          <a id="messages-dropdown" href="#" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Messages</a>
          <div id="messages-box"class="messages-box dropdown-menu dropdown-menu-right p-4" aria-labelledby="messages-dropdown">
            <%= render partial: 'shared/message_dropdown' %>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <div class="profile-box-sm">
          <a class="btn" id="dropdownMenuButton" data-toggle="collapse" data-target= "#account-collapse" aria-controls="account-collapse" aria-expanded="false" aria-label="Toggle navigation">
            Profile  <i class="fas fa-angle-down"></i>
          </a>
        </div>
        <div id="account-collapse" class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%=link_to "Your Profile", profile_path(current_user.id), class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%=link_to "Edit Profile", user_edit_path(current_user.id), class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" disabled>Invite Friends</a>
            </li>
            <li class="nav-item">
              <%=link_to "Account Settings", user_account_settings_path(current_user.id), class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <div id="header" class="btn ">
                <% if signed_in? -%>
                  <%= button_to(t(".sign_out"), sign_out_path, method: :delete, class: "btn p-0 bg-transparent") %>
                <% else -%>
                  <%= link_to t(".sign_in"), sign_in_path, class: "btn p-0" %>
                <% end -%>
              </div>
            </li>
          </ul>
        </div>
      </li>

      <!-- Account Dropdown -->
      <li class="nav-item">
        <div class="dropdown mx-2 profile-box">
          <a class="" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="rounded-circle" src="<%=current_user.avatar.url%>" style="width:35px;height:35px;">
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/profile/<%=current_user.id%>">Your Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/profile/<%=current_user.id%>/edit">Edit Profile</a>
            <a class="dropdown-item" href="#">Invite Friends</a>
            <a class="dropdown-item" href="/users/<%=current_user.id%>/account">Account Settings</a>
            <div class="dropdown-divider"></div>
            <div id="header" class="btn dropdown-item">
              <% if signed_in? -%>
                <%= button_to(t(".sign_out"), sign_out_path, method: :delete, class: "btn p-0 bg-transparent") %>
              <% else -%>
                <%= link_to t(".sign_in"), sign_in_path, class: "btn p-0" %>
              <% end -%>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>


</nav>
<script>
$('.messages-box').on('click', function(e) {
  e.stopPropagation();
});
</script>

app/views/shared/_search_listing.html.erb
<h5 class="font-weight-bold mb-4 text-center">Search by:<%=params[:search]%></h5>
<%=form_tag(search_listing_path , method: :get, remote:true, class: "d-flex justify-content-center") do %>
<%= text_field_tag(:search, params[:search], class: "shadow-sm form-control m-3 mb-5  w-50", placeholder: "Search by Name") %>
<% end %>

<div class="d-flex flex-row">
  <div class="px-2  tiny-font flex-shrink-1 font-weight-bold">ID</div>
  <div class="px-2  tiny-font col-2 font-weight-bold">Name</div>
  <div class="px-2  tiny-font col-2 font-weight-bold">Property Type</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">Country</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">State</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">Price</div>
  <div class="px-2  tiny-font col-2 font-weight-bold">Host</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">Verified</div>
</div>
<hr/>
<% Listing.search_by_name(params[:search]).each do |listing|%>
  <%= link_to view_listing_path(listing.id), remote: true, data: { target: "#listing-modal", toggle: 'modal' } do %>
  <div class="d-flex flex-row">
    <div class="px-2  tiny-font flex-shrink-1 font-weight-bold"><%=listing.id%></div>
    <div class="px-2  tiny-font col-2"><%=listing.name%></div>
    <div class="px-2  tiny-font col-2"><%=listing.property_type%></div>
    <div class="px-2  tiny-font col-1"><%=listing.country%></div>
    <div class="px-2  tiny-font col-1"><%=listing.state%></div>
    <div class="px-2  tiny-font col-1"><%=number_to_currency(listing.price, unit: '$')%></div>
    <div class="px-2  tiny-font col-2"><%=listing.user.name%></div>
    <div class="px-2 tiny-font col-1">
      <% if listing.verified? %>
        <p class="font-weight-bold text-success">Verified</p>
      <% else %>
        <p class="font-weight-bold text-warning">Not Verified</p>
      <% end %>
    </div>
  </div>
  <% end %>
<hr/>
<% end %>

app/views/shared/_unverified_listings.html.erb
<h5 class="font-weight-bold mb-4 text-center">Unverified Listings</h5>
<%=form_tag(search_listing_path , method: :get, remote:true, class: "d-flex justify-content-center") do %>
<%= text_field_tag(:search, params[:search], class: "shadow-sm form-control m-3 mb-5  w-50", placeholder: "Search by Name") %>
<% end %>
<div class="d-flex flex-row">
  <div class="px-2  tiny-font font-weight-bold">ID</div>
  <div class="px-2  tiny-font col-2 font-weight-bold">Name</div>
  <div class="px-2  tiny-font col-2 font-weight-bold">Property Type</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">Country</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">State</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">Price</div>
  <div class="px-2  tiny-font col-2 font-weight-bold">Host</div>
  <div class="px-2  tiny-font col-1 font-weight-bold">Verify</div>
</div>
<hr/>
<% Listing.where(verified: false).each do |listing|%>
    <div class="d-flex flex-row">
      <div class="px-2  tiny-font font-weight-bold"><%=listing.id%></div>
      <div class="px-2  tiny-font col-2"><%=listing.name%></div>
      <div class="px-2  tiny-font col-2"><%=listing.property_type%></div>
      <div class="px-2  tiny-font col-1"><%=listing.country%></div>
      <div class="px-2  tiny-font col-1"><%=listing.state%></div>
      <div class="px-2  tiny-font col-1"><%=number_to_currency(listing.price, unit: '$')%></div>
      <div class="px-2  tiny-font col-2"><%=listing.user.name%></div>
      <%=check_box("listings","verified", {id: "verify-listing-#{listing.id}", class: 'px-2  tiny-font col-1'}, true, false)%>
    </div>
    <hr/>
    <script>
    $('#verify-listing-<%=listing.id%>').change(function(){
      if (this.checked){
        $.ajax({
          type: 'POST',
          url: '/unverified_listings/<%=listing.id%>/verify/true',
          data: {verified: this.checked},
          success: function(data){
            alert('Listing ID <%=listing.id%> has been verified!');
            $(this).submit();
          }
        })
      }
    })
    </script>
<% end %>

app/views/shared/_verified-listings.html.erb
<h3 class="font-weight-bold mb-4">Pending Verification</h3>
<div class="row">
  <div class="col-1 font-weight-bold">ID</div>
  <div class="col-2 font-weight-bold">Name</div>
  <div class="col-1 font-weight-bold">Property Type</div>
  <div class="col-2 font-weight-bold">Country</div>
  <div class="col-2 font-weight-bold">State</div>
  <div class="col-1 font-weight-bold">Price</div>
  <div class="col-2 font-weight-bold">Host</div>
  <div class="col-1 font-weight-bold"><p class="m-0 text-left">Verify</p></div>
</div>
<hr/>
<% Listing.where(verified: true).each do |listing|%>
  <%= link_to view_listing_path(listing.id), remote: true, data: { target: "#listing-modal", toggle: 'modal' } do %>
    <div class="row">
      <div class="col-1"><%=listing.id%></div>
      <div class="col-2"><%=listing.name%></div>
      <div class="col-1"><%=listing.property_type%></div>
      <div class="col-2"><%=listing.country%></div>
      <div class="col-2"><%=listing.state%></div>
      <div class="col-1"><%=number_to_currency(listing.price, unit: '$')%></div>
      <div class="col-2"><%=listing.user.name%></div>
      <div class="col-1"><p class="font-weight-bold">Verified</p></div>
    </div>
  <%end%>
<hr/>
<% end %>

app/views/shared/_verified_listings.html.erb
<h3 class="font-weight-bold mb-4">Pending Verification</h3>
<div class="row">
  <div class="col-1 font-weight-bold">ID</div>
  <div class="col-2 font-weight-bold">Name</div>
  <div class="col-1 font-weight-bold">Property Type</div>
  <div class="col-2 font-weight-bold">Country</div>
  <div class="col-2 font-weight-bold">State</div>
  <div class="col-1 font-weight-bold">Price</div>
  <div class="col-2 font-weight-bold">Host</div>
  <div class="col-1 font-weight-bold"><p class="m-0 text-left">Verify</p></div>
</div>
<hr/>
<% Listing.where(verified: true).each do |listing|%>
  <%= link_to view_listing_path(listing.id), remote: true, data: { target: "#listing-modal", toggle: 'modal' } do %>
    <div class="row">
      <div class="col-1"><%=listing.id%></div>
      <div class="col-2"><%=listing.name%></div>
      <div class="col-1"><%=listing.property_type%></div>
      <div class="col-2"><%=listing.country%></div>
      <div class="col-2"><%=listing.state%></div>
      <div class="col-1"><%=number_to_currency(listing.price, unit: '$')%></div>
      <div class="col-2"><%=listing.user.name%></div>
      <div class="col-1"><p class="font-weight-bold">Verified</p></div>
    </div>
  <%end%>
<hr/>
<% end %>

app/views/shared/_view-users.html.erb
<h3 class="font-weight-bold mb-4">All Users</h3>
<div class="row">
  <div class="col-1 font-weight-bold">ID</div>
  <div class="col-2 font-weight-bold">First Name</div>
  <div class="col-1 font-weight-bold">Last Name</div>
  <div class="col-2 font-weight-bold">Birthday</div>
  <div class="col-2 font-weight-bold">Email</div>
  <div class="col-1 font-weight-bold">Phone</div>
  <div class="col-2 font-weight-bold">Country</div>
  <div class="col-1 font-weight-bold">Profile</div>
</div>
<hr/>
<% User.order(created_at: :desc).each do |user|%>
<div class="row">
  <div class="col-1"><a href='/users/<%=user.id%>'><%=user.id%></a></div>
  <div class="col-2"><%=user.first_name%></div>
  <div class="col-1"><%=user.last_name%></div>
  <div class="col-2"><%=user.birthday%></div>
  <div class="col-2"><%=user.email%></div>
  <div class="col-1"><%=user.phone%></div>
  <div class="col-2"><%=user.country%></div>
  <div class="col-1"><a href='/profile/<%=user.id%>'>Link</a></div>
</div>
</div>
<hr/>
<% end %>