config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  get '/home' => 'home#index', as: "home"

  # Home Route
  get "/home/load" => "home#load_content", as: "load_content"

  # Dome Route
  resources :dome, controller: "dome", only: [:index]
  get "/dome/:place_type" => 'dome#show_place_type', as: "show_place_type"
  get "/dome/show/all" => 'dome#show_all', as: "show_all"
  get "/dome/guests/:no1-:no2" => 'dome#show_by_guests', as: "show_by_guests"
  get "/dome/price/:no1-:no2" => 'dome#show_by_price', as: "show_by_price"


  # Listings Routes
  resources :listings, controller: "listings", only: [:show] do
    # Review Route
    resources :reviews, controller: "review", only: [:new, :create]
    get 'booked_dates' => 'reservations#booked_dates'
    # Reservations Route
    post 'reservations/review_booking', as: 'review_booking'
    resources :reservations do
      # Payment
      get 'payment/new'
      post 'payment/checkout'
    end
  end


  get '/my-listings' => 'listings#my_index', as: "my_listings"
  get '/my-listings/new' => 'listings#new', as: "new_listing"
  post '/my-listings/new' => 'listings#create'
  get '/my-listings/:id/edit' => 'listings#edit', as: "edit_listing"
  get '/get_property_from_place_type' => 'listings#property_from_place_type'
  delete '/my-listings/:id' => "listings#destroy", as: "delete_listing"
  get "/listing/:id/upload-photos" => 'listings#show_upload', as: "show_upload"
  post '/listings/:id/upload-photos' => "listings#upload_photos", as: "listing_upload_photos"
  delete '/listings/:id/remove-photo/:index' => "listings#remove_photo", as: "listing_remove_photo"
  get '/listings/:id/view-photos' => "listings#view_photos", as: "view_photos"

  get '/forgot-password' => 'passwords#new', as: 'forgot_password'
  resources :password, controller: "passwords", only: [:create]

  # Users Routes
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "passwords",
      only: [:edit, :update]

    get 'account' => 'account#index', as: 'account_settings'
    get 'account/security' => 'account#security', as: 'account_settings_security'
    patch 'account/security/password-update' => 'account#update_password', as: 'account_settings_password_update'
  end
  get "/sign_up" => "users#new", as: "sign_up"
  get "/profile/:id" => "users#show", as: "profile"
  get "/profile/:id/edit" => "users#edit", as: "user_edit"
  patch "/profile/:id/edit" => "users#update", as: "user"
  get "/:id/upload-photo" => "users#upload_photo", as: "user_upload_photo"
  get "/:id/remove-photo" => "users#remove_photo", as: "user_remove_photo"

  # Superadmin
  constraints Clearance::Constraints::SignedIn.new { |user| user.superadmin? } do
  get "/admin-panel" => "superadmin#index", as: "admin_panel"
  get "/all-users" => "superadmin#all_users", as: "view_users"
  get "/update-users" => "superadmin#update_users", as: "update_users"
  delete "/delete/:id" => "superadmin#destroy_user", as: "destroy_user"
  get "/update/:id" => "superadmin#edit_user", as: "edit_user"
  patch "/update/:id" => "superadmin#confirm_edit", as: "superadmin_edit_user"
  get "/admin/search" => "superadmin#search", as: "search_user"
  end
  # Moderator
  constraints Clearance::Constraints::SignedIn.new { |user| user.moderator? || user.superadmin? } do
  get "/moderator-panel" => "moderator#index", as: "moderator_panel"
  get "/unverified_listings" => "moderator#unverified_listings", as: "unverified_listings"
  post "/unverified_listings/:id/verify/:verified" => "moderator#verify"
  get "/verified-listings" => "moderator#verified_listings", as: "verified_listings"
  get "/all-listings" => "moderator#all_listings", as: "all_listings"
  get "/view-listing/:id" => "moderator#view_listing", as: "view_listing"
  get "/moderator-edit-listing/:id" => "moderator#edit_listing", as: "moderator_edit_listing"
  get "/moderator-delete-listing/:id" => "moderator#delete_listing", as: "moderator_delete_listing"
  delete "/moderator-delete-listing/:id" => "moderator#destroy_listing", as: "moderator_destroy_listing"
  get "/moderator/search" => 'moderator#search', as: 'search_listing'
  end
  # Sessions Routes
  resource :session, controller: "sessions", only: [:create]
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  # Google OAuth Route
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/controllers/dome_controller.rb
class DomeController < ApplicationController
  before_action :require_login
  def index
    @pagination = Listing.order(:created_at).page params[:page]
    @listings = PgSearch.multisearch(params[:search]).map do |m|
                  Listing.find(m.id)
                end
    respond_to do |format|
    format.html
    end
  end

  def show_all
    @all_listings = Listing.all
    @pagination = @all_listings.page params[:page]
    respond_to do |format|
      format.html { render 'dome/index' }
      format.js
    end
  end

  def show_place_type
    @place_type = Listing.where("place_type = ?", params[:place_type])
    @pagination = @place_type.page params[:page]
    respond_to do |format|
      format.html { render 'dome/index' }
      format.js
    end
  end

  def show_by_guests
    @guest_number = Listing.where("guest_number >= :one AND guest_number <= :two", {one: params[:no1], two: params[:no2]})
    @pagination = @guest_number.page params[:page]
    respond_to do |format|
      format.js
    end
  end

  def show_by_price
    @price = Listing.where("price >= :start AND price <= :end", {start: params[:no1], end: params[:no2]})
    @pagination = @price.page params[:page]
    respond_to do |format|
      format.html { render 'dome/index'}
      format.js
    end
  end
end

app/views/dome/_place_type.html.erb
<div id="listings">
  <div class="flexbox-card d-flex flex-wrap flex-row">
    <% @place_type.page(params[:page]).each do |home|%>
      <div id="home-card-<%=home.id%>" class="domecard card first p-0 m-2 shadow-sm btn">


        <!-- Carousel -->

        <!-- If listing has photos -->
        <% if home.photos? == true %>
            <div id="carousel-<%=home.id%>" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner">
                <% home.photos.each_with_index do |photo, index| %>
                    <% if index == 0 %>
                        <div class="carousel-item active">
                          <div class="img-box">
                            <%=image_tag(photo.thumb_large.url, class: 'd-block w-100', style: 'max-width: 300px; max-height: 200px;')%>
                          </div>
                        </div>
                    <% else %>
                        <div class="carousel-item">
                          <div class="img-box">
                            <%=image_tag(photo.thumb_large.url, class: 'd-block w-100', style: 'max-width: 300px; max-height: 200px;')%>
                          </div>
                        </div>
                    <% end %>
                <%end%>
              </div>
              <a class="carousel-control-prev" href="#carousel-<%=home.id%>" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carousel-<%=home.id%>" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>

        <!-- If listing has no photos -->
        <% else %>
        <%=image_tag('default2.jpg', class: 'd-block w-100', style: 'max-width: 300px; max-height: 200px;')%>
        <% end %>


        <!-- Details card about listing -->
        <%= link_to listing_path(home.id), target: '_blank' do %>
          <div class="card-body pb-1">
            <p class="card-subtitle text-muted"><%=home.property_type%></p>
            <ul class="list-inline">
              <li class="list-inline-item"><p class="card-title font-weight-bold mb-2"><%=home.name%></p></li>


              <!-- If home is verified, this will show -->
              <% if home.verified %>
              <li class="list-inline-item">
                <i id="verified-badge-thumbnail" class="fas fa-check-circle text-success"></i>
              </li>
              <% end %>
            </ul>
            <ul class="list-inline">
              <li class="list-inline-item"><i class="fas fa-user"></i> <%=home.guest_number%></li>
              <li class="list-inline-item"><i class="fas fa-bed"></i> <%=home.room_number%></li>
              <li class="list-inline-item"><i class="fas fa-bath"></i> <%=home.bathroom_number%></li>
            </ul>
            <p class="card-text">From <%=number_to_currency(home.price, unit: "$")%> a night</p>
          </div>

          <!-- Rating -->
          <div class="rating-box mb-3">
            <ul id="star-rating" class="list-inline">
              <li class="list-inline-item star"><i data-value='1' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
              <li class="list-inline-item star"><i data-value='2' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
              <li class="list-inline-item star"><i data-value='3' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
              <li class="list-inline-item star"><i data-value='4' id="star-<%=home.id%>" class="tiny-font rate-star far fa-star"></i></li>
              <li class="list-inline-item star"><i data-value='5' id="star-<%=home.id%>" class="tiny-font rate-star far fa-star"></i></li>
            </ul>
          </div>
        <% end %>
      </div>

      <div id="home-card-<%=home.id%>" class="domecard-sm card p-0 m-2 shadow-sm btn w-100">

        <!-- Details card about listing -->
        <%= link_to listing_path(home.id), target: '_blank' do %>
        <div class="row ml-0">
              <!-- If listing has photos -->
              <% if home.photos? == true %>
              <div class="domecard-img-sm col-4" style="background-image: url(<%=home.photos[0].thumb_large.url%>); background-position: center; background-size: cover;">
              </div>

              <!-- If listing has no photos -->
              <% else %>
                <%=image_tag('default2.jpg', class: 'd-block img-fluid w-100')%>
              <% end %>

            <div class="card-body p-2 col-8">
              <p class="card-subtitle text-muted"><%=home.property_type%></p>
              <ul class="list-inline mb-1">
                <li class="list-inline-item"><p class="card-title font-weight-bold mb-2"><%=home.name%></p></li>


                <!-- If home is verified, this will show -->
                <% if home.verified %>
                <li class="list-inline-item">
                  <i id="verified-badge-thumbnail" class="fas fa-check-circle text-success"></i>
                </li>
                <% end %>
              </ul>
              <ul class="list-inline mb-1">
                <li class="list-inline-item"><i class="fas fa-user"></i> <%=home.guest_number%></li>
                <li class="list-inline-item"><i class="fas fa-bed"></i> <%=home.room_number%></li>
                <li class="list-inline-item"><i class="fas fa-bath"></i> <%=home.bathroom_number%></li>
              </ul>
              <p class="card-text m-0">From <%=number_to_currency(home.price, unit: "$")%> a night</p>
              <!-- Rating -->
              <div class="rating-box">
                <ul id="star-rating" class="list-inline m-0">
                  <li class="list-inline-item star"><i data-value='1' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item star"><i data-value='2' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item star"><i data-value='3' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item star"><i data-value='4' id="star-<%=home.id%>" class="tiny-font rate-star far fa-star"></i></li>
                  <li class="list-inline-item star"><i data-value='5' id="star-<%=home.id%>" class="tiny-font rate-star far fa-star"></i></li>
                </ul>
              </div>
            </div>


          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<div class="nav-link d-flex flex-row justify-content-center">
<%= paginate @pagination %>
</div>

app/views/dome/_search.html.erb
<div id="listings-search">
    <div class="flexbox-card d-flex flex-wrap flex-row">
      <% @listings.each do |home|%>
          <div id="home-card-<%=home.id%>" class="domecard card first p-0 m-2 shadow-sm btn">
            <!-- Carousel -->

            <!-- If listing has photos -->
            <% if home.photos? == true %>
                <div id="carousel-<%=home.id%>" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
                  <div class="carousel-inner">
                    <% home.photos.each_with_index do |photo, index| %>
                        <% if index == 0 %>
                            <div class="carousel-item active">
                              <div class="img-box">
                                <%=image_tag(photo.thumb_large.url, class: 'd-block w-100', style: 'max-width: 300px; max-height: 200px;')%>
                              </div>
                            </div>
                        <% else %>
                            <div class="carousel-item">
                              <div class="img-box">
                                <%=image_tag(photo.thumb_large.url, class: 'd-block w-100', style: 'max-width: 300px; max-height: 200px;')%>
                              </div>
                            </div>
                        <% end %>
                    <%end%>
                  </div>
                  <a class="carousel-control-prev" href="#carousel-<%=home.id%>" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carousel-<%=home.id%>" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>

            <!-- If listing has no photos -->
            <% else %>
            <%=image_tag('default2.jpg', class: 'd-block w-100', style: 'max-width: 300px; max-height: 200px;')%>
            <% end %>


            <!-- Details card about listing -->
            <%= link_to listing_path(home.id), target: '_blank' do %>
              <div class="card-body pb-1">
                <p class="card-subtitle text-muted"><%=home.property_type%></p>
                <ul class="list-inline">
                  <li class="list-inline-item"><p class="card-title font-weight-bold mb-2"><%=home.name%></p></li>


                  <!-- If home is verified, this will show -->
                  <% if home.verified %>
                  <li class="list-inline-item">
                    <i id="verified-badge-thumbnail" class="fas fa-check-circle text-success"></i>
                  </li>
                  <% end %>
                </ul>
                <ul class="list-inline">
                  <li class="list-inline-item"><i class="fas fa-user"></i> <%=home.guest_number%></li>
                  <li class="list-inline-item"><i class="fas fa-bed"></i> <%=home.room_number%></li>
                  <li class="list-inline-item"><i class="fas fa-bath"></i> <%=home.bathroom_number%></li>
                </ul>
                <p class="card-text">From <%=number_to_currency(home.price, unit: "$")%> a night</p>
              </div>

              <!-- Rating -->
              <div class="rating-box mb-3">
                <ul id="star-rating" class="list-inline">
                  <li class="list-inline-item star"><i data-value='1' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item star"><i data-value='2' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item star"><i data-value='3' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
                  <li class="list-inline-item star"><i data-value='4' id="star-<%=home.id%>" class="tiny-font rate-star far fa-star"></i></li>
                  <li class="list-inline-item star"><i data-value='5' id="star-<%=home.id%>" class="tiny-font rate-star far fa-star"></i></li>
                </ul>
              </div>
            <% end %>
          </div>

          <div id="home-card-<%=home.id%>" class="domecard-sm card p-0 m-2 shadow-sm btn w-100">

            <!-- Details card about listing -->
            <%= link_to listing_path(home.id), target: '_blank' do %>
            <div class="row ml-0">
                  <!-- If listing has photos -->
                  <% if home.photos? == true %>
                  <div class="domecard-img-sm col-4" style="background-image: url(<%=home.photos[0].thumb_large.url%>); background-position: center; background-size: cover;">
                  </div>

                  <!-- If listing has no photos -->
                  <% else %>
                    <%=image_tag('default2.jpg', class: 'd-block img-fluid w-100')%>
                  <% end %>

                <div class="card-body p-2 col-8">
                  <p class="card-subtitle text-muted"><%=home.property_type%></p>
                  <ul class="list-inline mb-1">
                    <li class="list-inline-item"><p class="card-title font-weight-bold mb-2"><%=home.name%></p></li>


                    <!-- If home is verified, this will show -->
                    <% if home.verified %>
                    <li class="list-inline-item">
                      <i id="verified-badge-thumbnail" class="fas fa-check-circle text-success"></i>
                    </li>
                    <% end %>
                  </ul>
                  <ul class="list-inline mb-1">
                    <li class="list-inline-item"><i class="fas fa-user"></i> <%=home.guest_number%></li>
                    <li class="list-inline-item"><i class="fas fa-bed"></i> <%=home.room_number%></li>
                    <li class="list-inline-item"><i class="fas fa-bath"></i> <%=home.bathroom_number%></li>
                  </ul>
                  <p class="card-text m-0">From <%=number_to_currency(home.price, unit: "$")%> a night</p>
                  <!-- Rating -->
                  <div class="rating-box">
                    <ul id="star-rating" class="list-inline m-0">
                      <li class="list-inline-item star"><i data-value='1' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
                      <li class="list-inline-item star"><i data-value='2' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
                      <li class="list-inline-item star"><i data-value='3' id="star-<%=home.id%>" class="tiny-font rate-star fas fa-star"></i></li>
                      <li class="list-inline-item star"><i data-value='4' id="star-<%=home.id%>" class="tiny-font rate-star far fa-star"></i></li>
                      <li class="list-inline-item star"><i data-value='5' id="star-<%=home.id%>" class="tiny-font rate-star far fa-star"></i></li>
                    </ul>
                  </div>
                </div>


              </div>
            <% end %>
          </div>
      <% end %>
    </div>
</div>

app/views/dome/index.html.erb
<% content_for :navbar do %>
  <% if signed_in? %>
    <%= render partial: "shared/navbar" %>
  <% else %>
    <%= render partial: "shared/navbar-index" %>
  <% end %>
<% end %>
<%=form_tag(dome_index_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search], class: "searchbox-sm shadow-sm form-control mb-4", placeholder: "Search anything...") %>
<% end %>

<!-- Filter Bar -->
<div id="attrBar" class="container-fluid p-3">
  <ul class="list-inline m-0">
    <li class="list-inline-item">
      <!-- Show All -->
      <%=link_to "Show All", show_all_path, remote:true, class: 'btn btn-outline-secondary'%>
    </li>
    <li class="list-inline-item">
      <!-- Place -->
      <div class="dropdown">
        <button class="btn btn-outline-secondary " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Place
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%=link_to "Apartment", show_place_type_path(1), remote:true, class: 'dropdown-item'%>
          <%=link_to "House", show_place_type_path(2), remote:true, class: 'dropdown-item'%>
          <%=link_to "Secondary Unit", show_place_type_path(3), remote:true, class: 'dropdown-item'%>
          <%=link_to "Unique Space", show_place_type_path(4), remote:true, class: 'dropdown-item'%>
          <%=link_to "Boutique Hotel", show_place_type_path(5), remote:true, class: 'dropdown-item'%>
        </div>
      </div>
    </li>

    <li class="list-inline-item">
      <div class="dropdown">
        <!-- Guests -->
        <button class="btn btn-outline-secondary " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Guests
        </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%=link_to "1-5", show_by_guests_path(no1:1,no2:5), remote:true, class: 'dropdown-item'%>
            <%=link_to "6-10", show_by_guests_path(no1:6,no2:10), remote:true, class: 'dropdown-item'%>
            <%=link_to "11-15", show_by_guests_path(no1:11,no2:15), remote:true, class: 'dropdown-item'%>
            <%=link_to "16-20", show_by_guests_path(no1:16,no2:20), remote:true, class: 'dropdown-item'%>
          </div>
      </div>
    </li>

    <li class="list-inline-item">
      <div class="dropdown">
        <!-- Price -->
        <button class="btn btn-outline-secondary " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Price
        </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%=link_to "< $100", show_by_price_path(no1:1,no2:100), remote:true, class: 'dropdown-item'%>
            <%=link_to "$101 - $500", show_by_price_path(no1:101,no2:500), remote:true, class: 'dropdown-item'%>
            <%=link_to "$501 - $1000", show_by_price_path(no1:501,no2:1000), remote:true, class: 'dropdown-item'%>
            <%=link_to "> $1000", show_by_price_path(no1:1000,no2:2000), remote:true, class: 'dropdown-item'%>
          </div>
      </div>
    </li>

    <li class="list-inline-item">
      <div class="dropdown">
        <!-- Dates -->
        <!-- WORK IN PROGRESS -->
        <button class="btn btn-outline-secondary disabled" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dates
        </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            Hi
          </div>
      </div>
    </li>

    <li class="list-inline-item">
      <div class="dropdown">
        <!-- Instant Book -->
        <!-- Optional, not finalize -->
        <button class="btn btn-outline-secondary disabled" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Instant Book
        </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            Hello
          </div>
      </div>
    </li>

    <li class="list-inline-item">
      <div class="dropdown">
        <!-- More to be added soon here -->
        <button class="btn btn-outline-secondary disabled" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More Filters
        </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            Wat
          </div>
      </div>
    </li>
  </ul>
</div>
<div class="background-keep">
  <!-- If search is not used, this will be populated by all -->
  <div id="dome-content" class="mt-4">
      <% if params[:search] %>
        <%=render partial: 'dome/search', locale: @listings %>
      <% else %>
        <%=render partial: 'dome/show_all'%>
      <% end %>
  </div>
</div>

app/views/dome/show_all.js.erb
$('#dome-content').html('<%= j render "dome/show_all"%>');

app/views/dome/show_by_guests.js.erb
$('#dome-content').html("<%= j render 'dome/show_by_guests'%>");

app/views/dome/show_by_price.js.erb
$('#dome-content').html("<%= j render 'dome/show_by_price'%>");

app/views/dome/show_place_type.js.erb
$('#dome-content').html("<%= j render 'dome/place_type'%>");